benjamn/recast

package.json
This unblocks some projects mentioned here: https://github.com/facebook/esprima/issues/78
Please publish a new version of recast to npm with this change. Thanks!
=> Update to esprima-fb@9001.1.0-dev-harmony-fb

lib/options.js, lib/patcher.js, lib/printer.js, test/printer.js
@sebmarkbage on the React repo mentioned needing Recast to support a feature like this for them to support configurable quotemarks when compiling JSX transformations in the future. ([mentioned originally on pull request 1709](https://github.com/facebook/react/pull/1709))
=> Add tests and implementation for a "quotemark" printer option

test/printer.js
Adding a test for double comments bug. The comments are being double in the `Patcher` class but I'm not sure what the root issue is.
=> Add test for printer double comments bug.

lib/printer.js, package.json
Depends on benjamn/ast-types#93. I did a simple search/replace here as well and ran `npm test` with the updated ast-types version.
=> XJS -> JSX

lib/fast-path.js, lib/printer.js, test/printer.js
If an arrow function has one normal parameter and one rest parameter, recast will leave out the rest param when printing the arrow function. I've fixed the logic in printer.js and modified an existing unit test to exercise this code path.
**Note** this fix depends on this fix in ast-types: https://github.com/benjamn/ast-types/commit/39ac68d61b1a6c211245c87141c335ee7a2923a9
(apologies if there is a better way to express this dependency, or if I should be waiting to issue this pull request until the corresponding fix in ast-types is integrated)
=> fix arrow function print logic to better account for rest params

lib/fast-path.js, test/parens.js
In es6 arrow functions like this `(x, y) => x + y` the return statement is implicit. However, if the thing you're returning is an object literal, you need to surround it with parentheses (since curly braces are otherwise used to denote a function body).
Recast should add parentheses correctly in this situation.
Note: I wasn't sure where to add a unit test for this, but would be happy to do so if pointed in the right direction.
=> handle parentheses around object literals in arrow functions correctly

lib/printer.js, package.json, test/type-syntax.js
This adds printing for all flow/typescript syntax. I'll outline a few things in the comments. Note that this breaks 3 tests. It might be related to the `needsParens` code, but I'm unsure what to do to make the printing work. It seems that it prints `(function()() {})` now. @benjamn do you have an idea about this?
cc @jeffmo @gabelevi
=> Add ability to print Flow/TypeScript type annotations.

test/comments.js
(just reopening because I accidentally pushed this to master in my fork)
=> Add test that shows multiline function definitions get collapsed.

lib/options.js, lib/printer.js, test/printer.js
This adds support to print trailing commas, which is useful for code bases that adopted this style. They are only added if the corresponding list is split over multiple lines.
I had to add printing logic similar from function arguments to array expressions which, when `wrapColumn` is specified, tries to fit everything within the limit.
Are there any places that I missed where we should add trailing commas?
=> Print trailing commas when the `trailingComma` option is specified.

lib/printer.js, package.json, test/printer.js
This adds printing support for property initializers in "ES7".
Depends on https://github.com/benjamn/ast-types/pull/117 and https://github.com/benjamn/recast/pull/179 – I can remove the other recast diff though, just accidentally stacked it on top.
Fixes #188
=> Printing support for property initializers.

lib/printer.js, package.json, test/type-syntax.js
In https://github.com/facebook/esprima/commit/01e5f03ae650a228507504236ceb4ed06372e841 we updated how we use `import type` and added support for `import typeof`. We removed `isKind` and are instead relying on `importKind` which can be any of `value`, `type` or `typeof`. I made it so that it prints  `importKind` directly when it is not `value`.
I noticed also that there were minor bugs in the support for type printing. I discovered this because the ast in both cases was correct but the printed source was not. I changed the test to also directly compare the printed source, which required me to add newlines/spaces to the input source. That seemed better to me compared to using regex to remove newlines and spaces from the output. I will highlight some other fixes inline.
=> Fix import type/typeof and fix minor type printing issues.

lib/printer.js, test/printer.js
This adds support for printing template literals.
I did this pretty fast so let me know if I missed anything obvious. 
(Also sneaked in a small code update for printing ObjectExpressions and removed `should` from some tests).
=> Add support for printing template expressions.

lib/printer.js
The kind of MethodDefinition changed from init to method in ast-types. This fixes the printer.
=> Fix printing class methods

lib/printer.js
ESTree (esprima and Babel) puts the identifier name in the "local" property, not the "id" property.
See http://felix-kling.de/esprima_ast_explorer/#/3lOF4MIKlj and facebook/jscodeshift/issues/33
Do you want me to provide tests?
=> Fix printing import declarations

package.json
The update is just leaner and faster. https://github.com/mozilla/source-map/pull/203, https://github.com/mozilla/source-map/pull/204, https://github.com/mozilla/source-map/pull/205 and https://github.com/mozilla/source-map/pull/206
=> Upgrade source-map to ~0.5.0

lib/printer.js, test/printer.js
=> Always wrap arrow functions in parenthesis if the only param isn’t an identifier.

lib/printer.js
Now it can print by ast
```javascript
@decorator
class Some {
method() {
}
}
```
not only
```javascript
class Some {
@decorator
method() {
}
}
```
as yesterday
=> Print class decorators (not only class methods decorators)

lib/printer.js
Only print implements keyword if implements property has more than 0 items
Basically printing a `ClassExpression` adds an implements keyword. I'm guessing that this check here should really also check if the implements array is empty and that's why I get that result, because the default for `ClassExpression.implements` is `[]`.
Here's how this looks like:
http://astexplorer.net/#/mNvVofHYVs/1
cc @benjamn
=> Fix printing implements keyword

package.json
I'm trying to use https://github.com/reactjs/react-docgen with webpack.
However I'm getting the following error:
```
ERROR in ./~/recast/main.js
Module not found: Error: Cannot resolve module 'fs' in /Users/oliviertassinari/material-ui/docs/node_modules/recast
@ ./~/recast/main.js 18:4-17
```
This PR aim to fix it, following this PR https://github.com/jadejs/jade/pull/1644
=> [package] Support webpack

lib/fast-path.js, test/parens.js
Basically if the left hand expression of a callexpression is an arrow function we get this invalid output (when using `printGenerically`):
```js
()=>{}();
```
this output is invalid what it should be is:
```js
(()=>{})();
```
this pr fixes it and adds a spec for regressions.
cc @benjamn
=> Fix needsParens for `ArrowFunctionExpression`'s as callees

README.md
Makes a difference on retina displays. The gitter badge is already svg anyway so I assume you're cool with using them.
=> Change build badge to svg.

lib/comments.js, test/comments.js
Doing so doesn't break any existing tests.
@benjamn: This fixes a test case I have in my downstream project, and the provided test case.  If it doesn't have any unforeseen consequences, it may be a fix for #191 for most purposes.
=> Print trailing comments on statements as trailing

lib/printer.js, test/jsx.js
I'm not sure what the intention was behind the whitespace-stripping logic I removed. If there is a specific case that it was meant to handle, let me know and I can update this pull request with a test for it.
Fixes #246.
=> Preserve leading and trailing whitespace around string children of JSXElements

lib/util.js, test/babylon.js
This basically just does what it says. I don't know enough about the internals of recast to actually fix the problem, but now there's a tested failure case! :)
=> add failing test for decorators

lib/fast-path.js, test/babylon.js
The change itself is trivial - just adding `**` operator to PRECEDENCE table.
I'm not really sure about the proper way to test it. Added a test to Babylon test suite, which covers the problem that I was running into. Though it might seem more logical to include it to the general Parens test suite, but Esprima doesn't yet support this operator yet.
For reference: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
=> Add support for ES7 exponentiation operator

lib/options.js, lib/printer.js, test/printer.js
For users with eslint configured with `arrow-parens: always`.
=> Add singleArgumentArrowParenthesis option

lib/options.js, lib/printer.js, test/printer.js, test/type-syntax.js
Currently there are 2 supported syntaxes (`,` and `;`) in Flow Object Types. The use of commas is in line with the more popular style and matches how objects are defined in JS, making it a bit more natural to write. Recently we added a lint rule that enforces the use of commas, so it would great to have this option in recast as well. Thanks! 😃 
cc @cpojer
=> Add `flowObjectCommas` option

lib/printer.js, test/printer.js
=> No trailing comma for single-line flow object types

lib/fast-path.js, lib/printer.js, test/printer.js
Add parens for types like `?(string | number)`. Thanks!
=> Print parens for nullable union/intersection types

lib/util.js
Not all export declaration nodes have a `declaration` property. e.g. `export { MyObject, MyOtherObject}` has no `declaration` but an array of `specifiers`
When printing it will crash with an `TypeError: Cannot read property 'decorators' of null` error.
=> Fix assumption of declaration property on export

lib/printer.js, package.json
... to include `TypeParameter` information (https://github.com/benjamn/ast-types/commit/d5ce0400511bdf6b063c13728c4fa09edd9e122d). See also https://github.com/flowtype/flow-codemod/issues/6#issuecomment-233738594 .
This would also require a new (patch) release of recast.
=> Update to ast-types 0.8.18

lib/printer.js, test/es6tests.js, test/printer.js
When printing exported class or function declarations, recast currently prints an unnecessary trailing semicolon. This PR provides a fix to omit them.
These are the only two scenarios I could think of that would not require a semicolon.
=> Fix export trailing semicolon

lib/printer.js, test/printer.js
This is a minor stylistic change that adds spaces around `=` in function default parameters. Not sure if you'll take it but it's more aligned with the modern code styles/guidelines. Thanks!
=> Add spaces around `=` in AssignmentPattern (default parameters)

lib/parser.js, test/jsx.js
This is possible with the switch to Esprima 3.0 (PR #312).
=> Enable JSX by default

lib/options.js, lib/printer.js, lib/util.js, test/printer.js
Issue #335
The `trailingComma` option accepts an object that provides more granular control of where to enable/disable trailing commas.
e.g.
```javascript
trailingComma: {
objects: true, // Enable trailing commas in objects.
arrays: true, // Enable trailing commas in arrays.
parameters: false, // Disable trailing commas in function parameters.
}
```
=> Allow more granular control of trailing commas

lib/printer.js, test/printer.js
Seems like the Flow parser and Babylon all recognize `...rest` as a `RestElement`. Which parser uses `.rest` to represent it? :)
=> A RestElement should not have a trailing comma

lib/options.js, lib/printer.js, lib/util.js, test/printer.js
Let's make everyone happy 😎 . The idea is from #336.
The `spacing` option controls the printing of spaces inside array brackets and braces of object literals, destructuring assignments, and import/export specifiers.
This option could either be:
* Boolean - enable/disable in all contexts (object and arrays).
* Object - enable/disable per context.
Example:
```js
spacing: {
objects: true,
arrays: false,
},
```
cc @hzoo
=> Allow more granular control of spaces inside arrays/objects

lib/fast-path.js, test/parens.js, test/printer.js
Fixes the critical, long standing issue: #264 
Also fixes https://github.com/lebab/lebab/issues/105
=> Surround arrow functions with parenthesis when binding

lib/parser.js
This PR passes the `sourceFileName` through to the `File` node in `ast-types`.
It is dependant on `name` being added as an optional attribute to the `File` node. It thankfully is backwards compatible (in that it won't break anything) as it appears `ast-types` ignores any extra params.
The `ast-types` PR can be found at https://github.com/benjamn/ast-types/pull/200. More details of its use case there.
=> Add sourceFileName passthrough to File node

lib/lines.js, lib/patcher.js, lib/printer.js, test/comments.js, test/mapping.js, test/patcher.js
Fixes #362
If the argument to a return statement starts with a comment-only line, then we
now wrap it in parens to avoid the `return` getting parsed as its own line:
```js
function f() {
return (
// Foo
3
);
}
```
This problem can be introduced by adding a leading comment to any leftmost child
of the return argument, so we need to be more defensive about when we reformat
`return` statements. For now, we reprint the `ReturnStatement` node (but leave
unchanged children intact) when any child had changes.
=> Avoid an ASI bug by sometimes wrapping return expressions in parens

lib/fast-path.js
From https://github.com/babel/babel/issues/5579
b.memberExpression({type: "Literal", value: 1}, b.identifier('foo'))
outputs
(1).foo
but
b.memberExpression({type: "NumericLiteral", value: 1}, b.identifier('foo'))
outputs
1.foo
which is a syntax error.
Not sure where tests for this might belong, let me know if you want me to add some.
=> Add parens around Babel's numeric literals.

lib/patcher.js, test/babylon.js
This is not the right fix, but i couldn't figure out how to fix it properly. Babylon now tags nodes with an object:
```
extra: {
parenthesized: true,
parenStart: 0
}
```
I think Recast confuses it as a Node and then tries to reprint instead of using original node, causing iifes to be wrapped in parens.
=> Don't wrap IIFEs in parens when using babylon

lib/printer.js, package.json, test/type-syntax.js, yarn.lock
Opaque type docs: https://flow.org/en/docs/types/opaque-types/
Relevant AST explorer page: http://astexplorer.net/#/gist/ebf56525feda2ebea9d85b6eaca38a08/c9a154a07495bb895e44f845494d392f8e30527f
This commit also updates to the latest ast-types version with changes from https://github.com/benjamn/recast/pull/431
Test plan: Passes `yarn test`
=> Adds support for OpaqueType and DeclareOpaqueType

test/lines.js
Fixes #459 
Instead of using arguments.callee to create a fixture, hardcodes one that properly uses the operating system's eol (which is Recast's behavior, and rightly so).
I'm not 100% sure exactly what the original tests were looking for in the current function to test, but I tried to make fixtures that had similar properties.
=> Fix lines test so line endings don't get in the way on windows

lib/printer.js, test/babylon.js, test/printer.js
This fixes #457 
I still don't know if the existing behavior was by design, but if nothing else the PR can be a point of discussion. I'm also not sure if this approach is the preferred one, but I did my best to match the existing code. Esprima and Babylon handle this case pretty differently, and I had some trouble finding equivalent scenarios in the existing code.
Basically in babylon, numbers are parsed as NumericLiteral. If it's a non-base 10 number, the node has an "extra" field which contains a "raw" string, which itself contains whatever was parsed originally as is. In Esprima, the number is a plain Literal node with a raw property. I tried to make sure both cases are handled along with tests.
=> Preserve representation of numerics not in base 10

lib/printer.js
This PR fixes #452 
Although this PR would be workaround for the issue, it won't break regular cases.
=> Fix bug: avoid attaching "extends" to interface declarations.

lib/printer.js, test/type-syntax.js
In addition to an importKind on an ImportDeclaration (`import type {Foo} from 'bar'`), it's also valid to have an importKind on an ImportSpecifier (`import {type Foo} from 'bar'`).
Additionally, it's valid to have an exportKind on an ExportNamedDeclaration (`export type {Foo};`).
This adds support for both these cases, and a couple simple tests.
=> Add better support for importKind and exportKind

lib/printer.js
For example: `AssertionError [ERR_ASSERTION]: unexpected closingElement element in self-closing JSXElement`
square/babel-codemod#102
=> Improve the assertion message about self-closing JSX

parsers/_babylon_options.js
The following throws an error when using `@babel/parser@7.0.0-beta.52`:
```js
let parser = require('recast/parsers/babylon');
parser.parse('let foo = "whatever"');
```
With the following error:
```
'pipelineOperator' requires 'proposal' option whose value should be one of: minimal
```
This change to `parsers/_babylon_options.js` avoids the error.
I confirmed that this change does not cause issues when used with older `@babel/parser` versions (e.g. `7.0.0-beta.44`) or `babylon` (tested `6.18.9`).
=> Avoid error when using @babel/parser@7.0.0-beta.52+

lib/printer.js, test/babylon.js
The printer has a problem with the export-default-from syntax.
Instead of printing this:
```js
export foo, { bar } from 'foo';
```
we get this:
```js
export { foo, bar } from 'foo';
```
This PR adds a failing test for that case. (#480)
@benjamn I'm not really experienced with AST's but if this doesn't require too many changes and you think a beginner could tackle it, I'd try my best if you could point me to the relevant parts of the code 😊
=> Support the export-default-from syntax

lib/options.js
require("os").EOL may not be defined.  Use "\n" instead in this case.
Fixes #518
=> add a fallback for default options.lineTerminator

parsers/esprima.js
https://github.com/fkling/astexplorer/issues/334 mentions how syntax highlighting doesn't work for recast by default. So I noticed that the `range` option isn't passed along to esprima. 
We could of course also make it `true` by default.
=> Pass `range` option along to esprima parser.

lib/printer.js
I noticed that if you use the generic pretty printer it doesn't keep the comments. I'm not sure if this is the right approach, but it works?
=> Print comments when using the generic printer

lib/printer.js, test/comments.js
=> Fix #492: reprinting erroneously stripped comments attached to empty statements

lib/fast-path.js, lib/options.js, lib/parser.js, lib/patcher.js, lib/printer.js, parsers/_babylon_options.js, parsers/esprima.js, test/parens.js
Recast has suffered for a long time because it did not have reliable access to the lexical analysis of source tokens during reprinting, and instead relied on scanning source characters, which is error-prone because identifying comments, string literals, regular expression literals, and other large tokens is difficult/impossible without doing a full tokenization and sometimes a small amount of initial parsing.
Most importantly, accurate token information can be used to detect whether a node was originally wrapped with parentheses, even if those parentheses were separated from the node by comments or other incidental non-whitespace text, such as trailing commas. Here are just some of the issues that have resulted from the lack of reliable token information:
With this change, every node in …
=> Use node.loc.tokens to improve handling of parentheses.

lib/util.js, test/es6tests.js
This fixes an issue where exporting a template literal as default caused the parser to fail. It also adds a regression test.
Fixes #414
=> Fix issue with export default template literals

lib/comments.ts, lib/lines.ts, lib/mapping.ts, lib/printer.ts, lib/types.ts, test/lines.ts
When everything was converted to TypeScript, we intentionally held off on converting some existing constructor functions to proper classes.
This PR converts the `Mapping` and `Lines` types to classes.
=> Convert Lines to class.

lib/printer.ts
Update `printer.ts` to emit the access modifier for a field, as specified by [PR 323 for ast-types](https://github.com/benjamn/ast-types/pull/323).
=> Emit ClassProperty.access to specify field access

.travis.yml, README.md, lib/comments.ts, lib/fast-path.ts, lib/lines.ts, lib/mapping.ts, lib/parser.ts, lib/patcher.ts, lib/printer.ts, lib/types.ts, lib/util.ts, main.ts, package-lock.json, package.json, test/babel.ts, test/comments.ts, test/es6tests.ts, test/flow.ts, test/identity.ts, test/jsx.ts, test/mapping.ts, test/parens.ts, test/parser.ts, test/patcher.ts, test/perf.ts, test/printer.ts, test/syntax.ts, test/typescript.ts, test/visit.ts
Using `Object.defineProperties` to populate the `exports` object in `main.ts` is an ancient holdover from CommonJS. Now that this repository uses TypeScript (#554), we should embrace TS/ESM syntax as fully as possible.
From an external perspective, the most important change here is that the `recast` package no longer has a `default` export, and now uses only named exports.
Some exported types (`ASTNode`, `NodePath`, and `Type`) are no longer exported directly from `main.ts`, but may instead be obtained via `recast.types.{ASTNode,NodePath,Type}`.
These changes definitely necessitate a minor version bump, at the very least.
=> Modernize and TypeScript-ify the main.ts entry point module.

lib/printer.ts, test/printer.ts
OptionalMemberExpression has `optional` property which defines wether `?` is printed or not.
Try e.g `a?.b.c.d;` in [AST explorer](https://astexplorer.net/) to see how OptionalMemberExpression with optional=false is used.
E: ping @benjamn
=> Fix optional member expression printer

test/comments.ts
It's hacky though. See also #440: this pullreq removes those two `throw` statements. The change *seems* harmless...
=> Quick Patch for issue #440

lib/printer.ts, test/flow.ts, test/typescript.ts
added code to print `typeParamentes` for:
- FunctionExpression (case when it is anonymous function)
- NewExpression
- CallExpression
=> Fix printing expressions with type parameters

lib/printer.ts, test/babel.ts
This description will use the following code for illustration:
```js
(function () {
"use strict";
hello;
})();
```
In the situation where the containing `BlockStatement` changed but the directive itself did not, recast would simply print the directive as-is while generically printing the block. Since the `Directive` node `loc` includes the trailing semicolon, that part gets printed as `"use strict";`. Subsequently, the `BlockStatement` printer would unconditionally add a semicolon part after each directive string. This caused recast to print a double semicolon in such circumstances, i.e. `"use strict";;`.
Originally reported in https://github.com/codemod-js/codemod/issues/157.
=> Add semicolons after directives only as needed.

lib/printer.ts, test/printer.ts
Fixes [this](https://github.com/benjamn/ast-types/issues/348) issue
=> Add ability to have shorthand destructuring for default function parameter objects

lib/fast-path.ts, test/printer.ts
Add parenthesis around arrow function body when returning object literal with typescript typecast
```ts
() => ({} as object);
```
=> parenthesis around arrow function body when returning object literal

lib/printer.ts, test/typescript.ts
fix for the case when printing:
```ts
type Class<T> = new (...args: any) => T;
```
=> fix TSConstructorType printing

lib/comments.ts, lib/fast-path.ts, lib/lines.ts, lib/mapping.ts, lib/options.ts, lib/parser.ts, lib/patcher.ts, lib/printer.ts, lib/util.ts, test/babel.ts, test/comments.ts, test/es6tests.ts, test/flow.ts, test/identity.ts, test/jsx.ts, test/lines.ts, test/mapping.ts, test/parens.ts, test/parser.ts, test/patcher.ts, test/perf.ts, test/printer.ts, test/syntax.ts, test/typescript.ts, test/visit.ts
This was done automatically using the following:
```
npm i @codemod/cli @resugar/codemod-declarations-block-scope
./node_modules/.bin/codemod -p @resugar/codemod-declarations-block-scope {src,test}/**/*.ts
```
@benjamn, if there's some reason not to do this let me know. Otherwise I'll merge in a few days.
=> refactor: use block scoping

lib/fast-path.ts, lib/lines.ts, lib/patcher.ts, lib/printer.ts, test/babel.ts, test/patcher.ts, test/printer.ts, test/visit.ts
This was done via codemod:
```
npm i @codemod/cli @resugar/codemod-functions-arrow
./node_modules/.bin/codemod -p @resugar/codemod-functions-arrow {lib,test}/*.ts
```
This only rewrites functions that have a single statement that returns a value.
=> refactor: use arrow functions where appropriate

lib/patcher.ts, lib/printer.ts, test/patcher.ts, test/printer.ts
Fix issues around:
- FunctionTypeParam when used without parenthesis like `number => string`.
- TypeAlias of FunctionTypeAnnotation
=> Fix Flow function type param

lib/printer.ts, test/babel.ts
It has been introduced in TypeScript 3.7 and [Babel 7.7](https://babeljs.io/blog/2019/11/05/7.7.0#typescript-37-10543-https-githubcom-babel-babel-pull-10543-10545-https-githubcom-babel-babel-pull-10545)
=> Add support for "declare" in TS class fields with Babel

lib/fast-path.ts, test/babel.ts
Input code:
```
2 * (n / 2) ** 0.5;
```
Was printed as:
```
2 * (n / 2 ** 0.5);
```
After the fix would be printed as in input.
was discovered here: https://github.com/zxbodya/flowts/issues/4
=> fix precedence for ** operator, to correctly parenthesize expressions

lib/printer.ts, test/typescript.ts
Ensure parentheses are printed for the case:
```ts
const highlight = (n => false) as (a: number) => boolean;
```
=> add parentheses for function expressions for TSAsExpression

lib/printer.ts, package-lock.json, package.json
Updating `printExportDeclaration` to expect `exportKind` to be not null for things like `export interface`
=> babel 7.9, support for typescript 3.8

lib/fast-path.ts, package-lock.json, package.json, test/run.sh
Some can't be updated yet, like mocha, which requires nodejs 8+.
=> Update build dependencies

lib/fast-path.ts, lib/printer.ts, package-lock.json, package.json, test/parens.ts, test/typescript.ts
Whenever we update the `ast-types` dependency, we have to make sure Recast has printer cases for any/all updated type definitions. This is why #727 was initially failing (as expected).
Will close #727.
=> Prepare for ast-types@0.13.4.

lib/printer.ts, test/printer.ts
When the `trailingComma` option is enabled, we shouldn't append a trailing comma to a rest spread.
Closes #559
=> Fix trailing comma in destructuring rest spread

package-lock.json, package.json, tsconfig.json
Much like [`@babel/runtime`](https://www.npmjs.com/package/@babel/runtime) for Babel, the [`tslib`](https://www.npmjs.com/package/tslib) package is a runtime library that TypeScript can leverage to emit fewer helper function declarations.
=> Use tslib to avoid repeatedly inlining helper definitions.

lib/printer.ts, test/printer.ts
Follow-up to #766, addressing a few issues:
1. The `ChainElement` type is an abstract supertype of `CallExpression` and `MemberExpression` (see https://github.com/benjamn/ast-types/pull/399), so [`switch (n.type)`](https://github.com/benjamn/recast/blob/ae0a51e9e75b892e8d6aa26eef6e6976742aab9a/lib/printer.ts#L244) will always see either `"CallExpression"` or `"MemberExpression"` and never `"ChainElement"`.
2. We need to keep the printing of `{Member,Call}Expression` aligned with the printing of `Optional{Member,Call}Expression`, at least until the latter types are fully deprecated by all parsers.
3. The optionality logic for call expressions was slightly off. Whether a `?.` is printed should not depend on the optionality of `n.callee`. This has been an issue since #511, per git blame.
=> Add more tests of chain expressions.

lib/printer.ts, test/flow.ts
Fixes #960
Print `<T>` of a function type annotation like `<T>(t:T) => T`.
=> Print FunctionTypeAnnotation.typeParameters

lib/fast-path.ts, test/parens.ts
The firstInStatement function was missing the first child of a
SequenceExpression because it needs to check both the type of the parent
*node* and the name of the parent *path element*, which are not the same
in this case.
This fix is a "minimal change" style; it should be correct even if it's
not beautiful.  A cleaner fix would probably involve changing the way
the loop finds nodes.
=> Parenthesize function at start of sequence

lib/printer.ts, test/printer.ts
These two characters are considered ordinary characters by JSON but line
terminators by ECMAScript (prior to ES2019).  When pretty-printing a
string containing either character, JSON.stringify leaves it unescaped.
The result in recast.prettyPrint is that fromString, which follows
ECMAScript definitions, converts it mistakenly to a newline character.
Escaping these characters manually when the intent is to generate
ECMAScript (rather than JSON) eliminates the problem.
=> Fix pretty-printing strings with \u2028 or \u2029

lib/fast-path.ts, lib/printer.ts, parsers/babel-ts.ts, test/parens-extra.ts, test/run.ts, test/typescript.ts
Fixes #1067
I am not sure the test is completely adequate, but I can verify that the bug is fixed in the minimal repro.
=> Fix missing parens in reprinted output

lib/printer.ts, test/typescript.ts
Closes #867.
`TSInterfaceBody` handling in `printer.ts` adds additional semicolons when `recast.print` is used. This produces not working and not parsable code. Anyways, `prettyPrint` works good, it do not look at source, and try to guess that semicolons is needed, but it's internal method that no one use.
This PR removes additional semicolons, and keeps code parsable for both cases: `prettyPrint` and `print`.
So internal from source code:
```ts
interface Hello {
hello: any;
}
```
`prettyPrint` will produce:
```ts
interface Hello {
hello: any
}
```
And `print` will produce:
```ts
interface Hello {
hello: any;
}
```
=> fix: additional semicolon in TSInterfaceBody

lib/printer.ts, test/printer.ts
Resolves #1012
This PR makes the printer aware of `definite` property in `ClassProperty` AST node, printing `!` when `true`
=> Print class property definite assignment assertions

lib/printer.ts, test/typescript.ts
This is very pretty similar to #868 but with `TsTypeLiteral`. We were working on a codemod that involves adding to a `type` and it was resulting in syntactically incorrect code like this (notice the `;,`):
```
type FooProps = {
bar: string;,
children?: React.ReactNode
}
```
We were able to `patch-package` but I figured I would make an upstream fix. Thank you!
=> fix: additional commas in TsTypeLiteral

README.md
Fixes #76. See discussion in that issue.
I chose `source.min.js` as a hopefully obvious target name, since that's the context where source maps are used most often. I guess `target.js` could also have been a good name too.
=> Update source map example to use less misleading file names

parsers/esprima.ts
according to [distinguishing-a-script-and-a-module](https://esprima.readthedocs.io/en/4.0/syntactic-analysis.html#distinguishing-a-script-and-a-module,),
we should pass `sourceType` option to the `esprima.parse` function.
we have `esprima.parseScript`, `esprima.parseModule` and a deprecated `esprima.parse`.
[[API] Explicitly distinguish parsing a module vs a script #1576](https://github.com/jquery/esprima/issues/1576)
=> add sourceType option for esprima

lib/printer.ts, test/typescript.ts
When using `recast.print` function, `override` keyword is not preserved on `ClassMethod` nodes.
Reproduction link https://astexplorer.net/#/gist/a5f747da23a3539448fb63ffe9f04c43/5be0fb3874deba008cd4251e2756b8adb9289bea
Original issue on jscodeshift https://github.com/facebook/jscodeshift/issues/513
=> Fix typescript override keyword printer

lib/printer.ts, test/flow.ts
And add test cases.
The first commit does this by basically copying from the "ClassDeclaration" case.
But there's so much in common between them -- it'd be nice to share most of this logic. Otherwise, as this breakage demonstrates, it's easy for one of them to lag behind in getting a feature the other has. So in the second commit, we unify the handling of "DeclareClass" (used for Flow "declare class …") with "ClassDeclaration" and "ClassExpression", which are already unified with each other.
The "implements" property on "DeclareClass" isn't yet known to ast-types -- I'll send a PR there for that. But it's already emitted by flow-parser, so the round-trip tests already work.
=> Support Flow "declare class" fully: type parameters, "extends", "implements"

lib/options.ts, lib/util.ts, package-lock.json, package.json, types/globals.d.ts
This PR makes recast browser compatible by using an `assert` polyfill which will only be used in the browser, because with Node.js `assert` is a built-in, as well as conditionally requires `os` only when executed with Node.js.
Closes #1235
=> feat: make lib browser compatible

lib/printer.ts, test/typescript.ts
This fixes a small oversight: `ExportSpecifier` supports `exportKind` in a similar fashion to `ImportSpecifier` supporting `importKind`, but the print logic was missing.
Without this change it's impossible to generate an ExportNamedDeclaration containing a mix of type and value exports.
See this [broken jscodeshift example in AST Explorer](https://astexplorer.net/#/gist/38d63e7f66c1d7a14014716483fca861/b50b4c4d23601c2f07bd634a3f9c0bd832b5d496)
This is in the spirit of changes described in the original [type-only PR for TypeScript](https://github.com/microsoft/TypeScript/pull/45998), as well as changes for [SWC in 1.2.92](https://github.com/swc-project/swc/pull/2309)
=> fix: print ExportSpecifier.exportKind

lib/fast-path.ts, test/printer.ts
Closes https://github.com/benjamn/recast/issues/1357
=> fix(print): wrap unary exprs inside `**` in parens

lib/comments.ts, lib/fast-path.ts, lib/lines.ts, lib/mapping.ts, lib/parser.ts, lib/patcher.ts, lib/printer.ts, lib/util.ts, package-lock.json, package.json
This is the same as #1387, but without the unrelated formatting changes. When bundled using `esbuild`, this brings the file size down from 852KB to 712KB, a savings of 140KB (16%).
=> refactor: replace `assert` with `tiny-invariant`

.github/workflows/main.yml, .prettierignore, lib/printer.ts, package.json, test/babel.ts, test/printer.ts, test/syntax.ts, test/typescript.ts, tsconfig.json
this is just the result of `npm run format`
makes sense to keep it up to date i think for future contributors
=> chore: run format

test/lines.ts
This was here since the `Lines` class was originally added in 1859d1441605516ecdad0a69be9c4242efae0513, but `exports.testBasic` was never defined and so this always was `undefined`.
=> test: remove useless test code

lib/printer.ts, package-lock.json, package.json, test/printer.ts
@egasimus let me know if this fixes your issue (and doesn't cause different issues).
Fixes #1390
=> fix: print export namespace specifiers without braces

lib/printer.ts, test/run.ts, test/tsx.ts
Supports actually parsing cases like `<Foo<Bar> />` instead of crashing.
Was unsure how to test this, since the existing code inherits from babel-parser's fixtures, and that doesn't currently have any tests of the sort (though it is a supported format).
Please let me know if there's any changes / modifications needed to the PR!
[Demonstration on Babel REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAERgNwDwBVEFMAeUuYAJgM6IDkAhgEYSUB8iAFAN6IAOATnJ4gF8AXIg48-InAICUogFCJE3XFBDckGEukQQANtTJkActQC2uALxs9B42dwDEAekYBuOQLlyMqTGSjcMGAA5sw2hibmFgBE0c5uckA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTr …
=> printer: Support type parameters on JSX components in TSX

lib/printer.ts, test/babel.ts, test/printer.ts, test/syntax.ts, test/typescript.ts, tsconfig.json
`TSMethodSignature` has a `kind` property which can be set to `method` (the default), `get`, and `set`. When `get` and `set`, the method is a getter or a setter, and as such, should be prefixed with either `get ` or `set `.
=> Update printer.ts to support `kind = 'get'/'set'` on `TSMethodSignature`

lib/lines.ts, test/lines.ts
Many of these could just be left inferred.
=> refactor: replace `any` type annotations in `Lines`
