- lib/fast-path.js
- lib/patcher.js
- lib/printer.js
- test/parser.js
- test/patcher.js
This implements the experiment proposed in #139.
> Remove types.NodePath dependency.

- package.json
- test/jsx.js
also add a failing test for multi-line comments (loc bug in esprima-fb, needs a fix upstream)
> bump esprima-fb, add some jsx tests, refs #175

- package.json
Includes a fix for seeing inline diffs (https://github.com/mochajs/mocha/pull/1655).
> Use mocha@~2.2.5

- test/comments.js
see https://github.com/benjamn/recast/issues/190
cc: @benjamn
> Add failing test for trailing body comments

- lib/printer.js
- test/printer.js
Travis will fail until I update package.json to the new ast-types version.
> Print RestElement with parenthesis in ArrowFunctionExpressions

- lib/printer.js
printer was missing the constructor kind
> Fixing missing constructor

- lib/printer.js
Tested on the codemod and it works :)
> Fixes #248

- lib/comments.js
- lib/parser.js
> Support babylon's CommentBlock, CommentLine types

- lib/printer.js
> Remove support for XJS nodes.

- lib/printer.js
- test/printer.js
Spiritual successor to #249. Thanks for reviewing! cc @spicyj
> Add support for printing return type in arrow function expression

- lib/printer.js
Ref https://github.com/babel/babel/pull/3561
Ref https://github.com/benjamn/ast-types/issues/132#issuecomment-161400284
Ref https://github.com/babel/babylon#output
> printer: add babel 6 nodes

- lib/printer.js
- test/jsx.js
Per the comment thread in https://github.com/benjamn/recast/issues/267, this seems like the best option to get this sorted out. Tests pass, which is cool.
This, of course, may not be the best option anymore. If that's the case, let me know and I'll close this 😄
> Revert bad jsx whitespace commit

- lib/printer.js
- test/printer.js
Similar to #313 -- minor stylistic change. Thanks!
> Add a new line for multi-line function params

- lib/printer.js
- package.json
- test/babylon.js
- test/printer.js
- test/type-syntax.js
Depends on https://github.com/benjamn/ast-types/pull/162 so can change the package.json after it's merged
> Babel 6 changes + flow

- lib/util.js
- test/babylon.js
I created issue #356 to explain this bug.
> Test demonstrating issue transforming code while using babylon parser

- package.json
Closes #389
https://greenkeeper.io/
> chore(package): update reify to version 0.6.2

- package.json
> chore(package): update reify to version 0.10.0

- lib/fast-path.js
- test/parens.js
> Fix parens for object destructuring assignment expression

- package.json
> chore(package): update reify to version 0.12.3

- package.json
> fix(package): update source-map to version 0.6.1

- package.json
> chore(package): update babylon to version 6.18.0

- package.json
> chore(package): update flow-parser to version 0.57.3

- package.json
> chore(package): update flow-parser to version 0.59.0

- package.json
> chore(package): update reify to version 0.14.1

- package.json
> chore(package): update flow-parser to version 0.65.0

- yarn.lock
I cloned the project and ran `yarn install` and got changes to `yarn.lock`.
> Re-sync yarn.lock.

- package.json
> chore(package): update flow-parser to version 0.67.1

- .travis.yml
- lib/fast-path.js
- test/run.sh
> Fix #504: parens around arrow function body expression

- lib/printer.js
- test/printer.js
> Add a printer case for flow tuple type annotations

- lib/printer.js
https://github.com/benjamn/ast-types/pull/272
https://github.com/tc39/proposal-optional-chaining
cc @qfox @cpojer
> Implement printer cases for Optional{Member,Call}Expression.

- lib/printer.js
> Honor 'declare' attribute for TSTypeAliasDeclaration nodes.

- lib/fast-path.js
- test/printer.js
Previously the code forgot to add sufficient parens.
fixes issue #516
> Fix printing of IIFEs as default exports

- package.json
> chore(package): update flow-parser to version 0.76.0

- package.json
> chore(package): update flow-parser to version 0.80.0

- package.json
> chore(package): update reify to version 0.17.3

- lib/printer.ts
- test/flow.ts
> Print typeAnnotation for ArrayPattern

- parsers/esprima.ts
- test/jsx.ts
> feat: recast:esprima supports jsx

- lib/printer.ts
- test/printer.ts
> fix: account for invalid shorthand properties

- lib/printer.ts
- package-lock.json
- package.json
> Update ast-types to v0.14.1 and implement missing Flow printer cases.

- lib/comments.ts
- package-lock.json
- package.json
Indirectly inspired by https://github.com/facebook/regenerator/pull/394.
Also took this opportunity to improve the use of TypeScript types in `lib/comments.ts` somewhat.
> Use WeakMap instead of outdated 'private' package.

- package-lock.json
- package.json
> Try updating to `typescript@4.3.5`

- package.json
> Rename prepack script to prepare, to allow installation from Git

- package-lock.json
- package.json
> Replace ts-emit-clean with tsc --build --clean

- lib/printer.ts
- test/typescript.ts
Fixes https://github.com/benjamn/recast/issues/1146.
> Fix disappearing TSModuleBlock curly braces

- package-lock.json
- package.json
This was the result of running `npm audit fix`.
> chore(dev-deps): update `mocha`

- lib/options.ts
- lib/printer.ts
- package-lock.json
- package.json
- parsers/babel.ts
- test/babel.ts
- test/printer.ts
- test/syntax.ts
- test/typescript.ts
Refs #1230
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiation-expressions. This won't work yet because `ast-types` does not yet know about `TSInstantiationExpression`. Once it does `recast` will need to be updated to include the newer release of `ast-types`, at which point it will be supported.
> Add support for `TSInstantiationExpression`
